local default = {
  icons = {
    File = "󰈙 ",
    Module = " ",
    Namespace = "󰦮 ",
    Package = " ",
    Class = "ﴯ ",
    Method = " ",
    Property = "ﰠ ",
    Field = " ",
    Constructor = " ",
    Enum = " ",
    Interface = " ",
    Function = " ",
    Variable = "󰀫 ",
    Constant = "󰏿 ",
    String = " ",
    Number = "󰎠 ",
    Boolean = "󰨙 ",
    Array = "󱡠 ",
    Object = " ",
    Key = "󰌋 ",
    Null = "󰟢 ",
    EnumMember = " ",
    Struct = " ",
    Event = " ",
    Operator = " ",
    TypeParameter = "󰊄 ",
  },
  highlight = false,
  separator = " > ",
  depth_limit = 0,
  depth_limit_indicator = "..",
  safe_output = true,
}

require("nvim-navic").setup(default)
